# Generated by Django 4.1.5 on 2023-01-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_watering_watered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watering',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='watering',
            old_name='cat',
            new_name='flower',
        ),
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateField(),
        ),
    ]
