# Generated by Django 4.1.5 on 2023-01-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_watering_options_rename_cat_watering_flower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='fertilizers',
            field=models.ManyToManyField(to='main_app.fertilizer'),
        ),
    ]
